import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar"; // Change 'navbar' to 'Navbar'



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Imane Arroub Portfolio ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   <body className={`${inter.className} h-[200vh]`}>

        
        <div className="w-screen h-screen bg-gradient-to-b from-blue-50 to to-black-100">
        <div className="h-24">
        <Navbar/>
        </div>
        <div className="h-svh">{children}</div>

        </div>
        </body>
    </html>
  );
}
